In [1]:
pip install numpy

   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
    --------------------------------------- 0.3/12.3 MB ? eta -:--:--
   - -------------------------------------- 0.5/12.3 MB 822.6 kB/s eta 0:00:15
   -- ------------------------------------- 0.8/12.3 MB 892.9 kB/s eta 0:00:13
   -- ------------------------------------- 0.8/12.3 MB 892.9 kB/s eta 0:00:13
   --- ------------------------------------ 1.0/12.3 MB 899.9 kB/s eta 0:00:13
   ---- ----------------------------------- 1.3/12.3 MB 867.5 kB/s eta 0:00:13
   ---- ----------------------------------- 1.3/12.3 MB 867.5 kB/s eta 0:00:13
   ----- ---------------------------------- 1.6/12.3 MB 833.4 kB/s eta 0:00:13
   ----- ---------------------------------- 1.6/12.3 MB 833.4 kB/s eta 0:00:13
   ----- ---------------------------------- 1.8/12.3 MB 796.1 kB/s eta 0:00:14
   ----- 

In [2]:
import numpy as np

In [3]:
arr1=[1,2,3,4,5]

In [4]:
ndarr1=np.array(arr1)

In [5]:
type(arr1)

list

In [6]:
type(ndarr1)

numpy.ndarray

In [7]:
arr2=[[1,2,3,],[1,2,3]]

In [8]:
arr2

[[1, 2, 3], [1, 2, 3]]

In [9]:
ndarr2=np.array(arr2)

In [10]:
ndarr2

array([[1, 2, 3],
       [1, 2, 3]])

תרגיל 1

In [11]:
arrRandom=np.random.randint(1,50)

In [12]:
arrRandom

10

In [17]:
arrRandom=np.random.randint(1,50,size=(3,3))

In [18]:
arrRandom

array([[41, 44,  5],
       [13, 24,  2],
       [31,  8, 24]], dtype=int32)

In [19]:
arrRandom.size

9

In [20]:
type(arrRandom)

numpy.ndarray

In [24]:
np.ndim(arrRandom)

2

תרגיל 2

In [25]:
arrRandom2=np.random.randint(10,100,size=(2,5))

In [26]:
arrRandom2

array([[61, 85, 51, 54, 17],
       [15, 85, 70, 80, 52]], dtype=int32)

In [27]:
np.shape(arrRandom2)

(2, 5)

תרגילים ש.ב

# 1.

In [29]:
arrRandom3=np.random.randint(10,100,size=(1,10))

In [30]:
np.mean(arrRandom3)

np.float64(72.0)

In [31]:
arrRandom3

array([[68, 41, 53, 59, 76, 86, 86, 92, 60, 99]], dtype=int32)

In [32]:
np.mean(arrRandom3)

np.float64(72.0)

# 2.

In [35]:
arrA= np.array([[1,2,3],[4,5,6]])

In [36]:
arrB= np.array([[11,22,33],[44,55,66]])

In [37]:
ab= np.add(arrA,arrB)

In [38]:
ab

array([[12, 24, 36],
       [48, 60, 72]])

In [39]:
np.mean(ab)

np.float64(42.0)

# 3.

In [40]:
arrRandom4=np.random.randint(1,100,size=(1,20))

In [41]:
arrRandom4

array([[26, 43, 84, 18, 30, 77, 24, 50, 61, 62,  8, 36, 99,  2, 16, 60,
        65, 68, 46, 66]], dtype=int32)

In [42]:
bigger50=arrRandom4 > 50

In [43]:
bigger50

array([[False, False,  True, False, False,  True, False, False,  True,
         True, False, False,  True, False, False,  True,  True,  True,
        False,  True]])

In [44]:
arr4=np.arange(1, 11)

In [45]:
arr4

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])